<?php
// $Id$

/**
 * @file
 *   Provides a file attachment search implementation for use with the Apache Solr module
 */

/**
 * Implementation of hook_menu().
 */
function apachesolr_attachments_menu() {
  $items = array();  
  $items['admin/settings/apachesolr/attachments'] = array(
    'title' => 'File attachments',
    'description' => 'Administer Apache Solr Attachments.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('apachesolr_attachments_settings'),
    'access callback' => 'user_access',
    'access arguments' => array('administer site configuration'),
    'type' => MENU_LOCAL_TASK,
  );
  return $items;
}

/**
 * Displays the Attachment Settings Form.
*/
function apachesolr_attachments_settings() {

  $form['apachesolr_attachments_tika_path'] = array(
    '#type' => 'textfield',
    '#title' => t('Tika directory path'),
    '#size' => 50,
    '#maxlength' => 100,
    '#description' =>  t("The full path to tika-0.3.jar.  All library jars must be in the same directory."),
    '#default_value' => variable_get('apachesolr_attachments_tika_path', ''),
  );

  $form = system_settings_form($form);
  $form['#validate'][] = 'apachesolr_attachments_settings_validate';
  return $form;
}

function apachesolr_attachments_settings_validate($form, &$form_state) {
  $path = realpath($form_state['values']['apachesolr_attachments_tika_path']);
  if (!file_exists($path . '/tika-0.3.jar')) {
    form_set_error('apachesolr_attachemnts_tika_path', t('Tika jar file not found at this path.'));
  }
}

/**
 * Implementation of hook_search().
 */
function apachesolr_attachments_search($op = 'search', $keys = NULL) {

  switch ($op) {
    case 'name':
      return ''; // We dont want a tab
    case 'reset':
      apachesolr_clear_last_index('apachesolr_attachments');
      return;
    case 'status':
      // TODO: Figure out a way to know how many actual files are left to update.
      return apachesolr_index_status('apachesolr_attachments');
    case 'search':
      return array();
  }
}

/**
 * Hook is called by search.module to add things to the search index.
 * In our case we will search content types and add any CCK type that
 * is a file type that we know how to parse and any uploaded file
 * attachments.
 */
function apachesolr_attachments_update_index() {
  if(!variable_get('apachesolr_attachments_tika_path', '')) {
    return;
  }

  $cron_limit = variable_get('apachesolr_attachments_cron_limit', 200);
  $result = apachesolr_get_nodes_to_index('apachesolr_attachments', $cron_limit);
  apachesolr_index_nodes($result,  'apachesolr_attachments', 'apachesolr_attachments_add_documents');
}

/**
 * Callback for apachesolr_index_nodes().
 *
 * Adds a document for each indexable file attachment for the given node ID.
 */
function apachesolr_attachments_add_documents(&$documents, $nid) {
  $node = node_load($nid, NULL, TRUE);
  if (!empty($node->nid)) {
    
    $hash = apachesolr_site_hash();

    // Since there is no notification for an attachment being unassociated with a 
    // node (but that action will trigger it to be indexed again), lets remove 
    // all indexed attachments then add all attached (if any)

    $fids = array();
    $result = db_query("SELECT fid FROM {apachesolr_attachments_files} WHERE nid = %d", $node->nid);
    while ($row = db_fetch_array($result)) {
      $fids[$row['fid']] = $row['fid'];
    }

    $files = _asa_get_indexable_files($node);
    // Find deleted files.
    $missing_fids = array_diff_key($fids, $files);
    if ($missing_fids) {
      db_query("UPDATE {apachesolr_attachments_files} SET removed = 1 WHERE fid IN (". db_placeholders($missing_fids) .")", $missing_fids);
    }
    $new_files = array_diff_key($files, $fids);
    // Add new files.
    foreach ($new_files as $file) {
      db_query("INSERT INTO {apachesolr_attachments_files} (fid, nid, removed) VALUES (%d, %d, 0)", $file->fid, $node->nid);
    }
    foreach ($files as $file) {
      $text = _asa_get_attachment_text($file);
      
       // Strip bad control characters. Do we need to make a hook for text cleanup?
      $text = trim(apachesolr_clean_text($text));

      if ($text) {
        $document = new Apache_Solr_Document();
        $document->id = apachesolr_document_id($file->fid, 'file');
        $document->url = file_create_url($file->filepath);
        $document->path = $file->filepath;
        $document->hash = $hash;
        $document->site = url(NULL, array('absolute' => TRUE));
        $document->nid = $node->nid;
        $document->title = $file->filename;
        $document->created = apachesolr_date_iso($file->timestamp);
        $document->changed = $document->created;
        $document->status = $node->status;
        $document->sticky = $node->sticky;
        $document->promote = $node->promote;
        $document->uid = $node->uid;
        $document->name = apachesolr_strip_ctl_chars($node->name);
        $document->body = apachesolr_clean_text($file->description) .' '. $text;

        $document->bsfield_file = TRUE;
        $document->ssfield_filemime = $file->filemime;
        $document->ssfield_file_node_title = apachesolr_clean_text($node->title);
        $document->ssfield_file_node_url = url('node/' . $node->nid, array('absolute' => TRUE));

        apachesolr_add_taxonomy_to_document($document, $node);
        
        drupal_alter('apachesolr_attachment', $document, $node, $file);
         
        $documents[] = $document;
      }
    }
  }
}

/**
 * Implementation of hook_nodeapi().
 *
 * For a delete: mark all associated attachments as removed.
 */
function apachesolr_attachments_nodeapi($node, $op) {

  switch ($op) {
    case 'delete':
      _asa_remove_attachments_from_index($node->nid);
      // Mark attachments for later re-deletion in case the query fails.
      db_query("UPDATE {apachesolr_attachments_files} SET removed = 1 WHERE nid = %d", $node->nid);
      break;
  }
}

/**
 * Implementation of hook_cron().
 *
 * Delete all removed attachments from the Solr store.
 */
function apachesolr_attachments_cron() {
  try {
    $solr = apachesolr_get_solr();
    $result = db_query("SELECT fid, nid FROM {apachesolr_attachments_files} WHERE removed = 1");
    $ids = array();
    $fids = array();
    while ($file = db_fetch_object($result)) {
      $ids[] = 'id:'. apachesolr_document_id($file->fid, 'file');
      $fids[] = $file->fid;
    }
    if ($ids) {
      $solr->deleteByQuery(implode(' OR ', $ids));
      $solr->commit();
      db_query("DELETE FROM {apachesolr_attachments_files} WHERE fid IN (". db_placeholders($fids) .")", $fids);
    }
  }
  catch (Exception $e) {
    watchdog('Apache Solr Attachments', $e->getMessage() . ' in apachesolr_attachments_cron', NULL, WATCHDOG_ERROR);
  }
}

/**
 * Implementation of hook_apachesolr_process_results().
 *
 * When using the core Apache Solr module, everythign is treated as a node and as such 
 * the link and type wont be configured correctly if it is a file attachement, so override 
 * those values here if needed. 
 */
function apachesolr_attachments_apachesolr_process_results($results) {

  if (is_array($results)) {
    foreach ($results as &$item) {
      if (isset($item['node']->bsfield_isfile) && $item['node']->bsfield_isfile === TRUE) {
        $nid = $item['node']->nid;
        $node_title = db_result(db_query("SELECT title FROM {node} WHERE nid = %d", $nid));
        $item['snippet'] = l($node_title, "node/$nid") . ': ' . $item['snippet'];
      }
    }
  }
}

/**
 * Return all non-indexed file attachments for a particular node
 */
function _asa_get_indexable_files($node) {
  $files = array();

  if(!empty($node->files)) {
    $files = array_merge($files, $node->files);
  }

  $fields = _asa_get_cck_file_fields();
  foreach ($fields as $field) {
    if(!empty($node->$field)) {
      $files = array_merge($files, $node->$field);
    }
  }
  $file_list = array();
  foreach ($files as $file) {
    // Some are arrays others are objects, treat them all as objects
    $file = (object) $file;
    if (isset($file->data['description']) && !isset($file->description)) {
      $file->description = $file->data['description'];
    }
    $file_list[$file->fid] = $file;
  }
  return $file_list;
}

/**
 * Return all CCK fields that are of type 'file'
 */
function _asa_get_cck_file_fields() {
  $file_fields = array();
  if(module_exists('filefield')) {
    $fields = content_fields();
    foreach($fields as $key => $values){
      if($values['type'] == 'filefield') {
        $file_fields[] = $key;
      }
    }
  }
  return $file_fields;
}

/**
 * Parse the Attachment getting just the raw text, stripping any garbage characters that
 * could screw up the XML Doc processing.
 */
function _asa_get_attachment_text($file) {

  if ($file->filemime == 'text/plain' || $file->filemime == 'text/x-diff') {
    return file_get_contents($file->filepath);
  }
  
  $tika_path = variable_get('apachesolr_attachments_tika_path', '');

  // Empty entries in settings mean that helper is disabled.
  $tika = $tika_path . '/tika-0.3.jar';

  $cmd = escapeshellcmd('java -cp '. $tika_path .' -jar '. $tika .' -t '. $file->filepath);
  $text = shell_exec($cmd);

  return $text;
}

/**
 * For a particular node id, remove all file attachments from the solr index.
 */
function _asa_remove_attachments_from_index($nid) {
  try {
    $solr = apachesolr_get_solr();
    $solr->deleteByQuery("nid:{$nid} AND bsfield_file:true AND hash:". apachesolr_site_hash());
    $solr->commit();
  }
  catch (Exception $e) {
    watchdog('Apache Solr Attachments', $e->getMessage(), NULL, WATCHDOG_ERROR);
  }
}

